service: slack-command-contents

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: ap-northeast-2
  
functions:
  contents:
    handler: handler.contents
    events: 
      - http:
          path: contents
          method: post